### ISSUE TITLE
is not working with rails 5.0

### ISSUE THREAD

**Issue by afmp94** [d0z0/redis_analytics#17]
i tried to use the gem. but it gives me an exception error.
cannot load such file -- rack/showexceptions
do i have to use sinatra?

**Comment by agrohmann** [comment]
+1 

/usr/local/bundle/gems/sinatra-1.0/lib/sinatra/showexceptions.rb:1:in `require': cannot load such file -- rack/showexceptions (LoadError)

**Comment by glaszig** [comment]
this error happens when you use an old version of sinatra. upgrade sinatra. see mperham/sidekiq#2839.

also, redis_analytics does not depend on sinatra (anymore, since some versions). it requires rails.
